# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Syntactic Sophistry
email: misternu@gmail.com
description: True knowledge lies in knowing you can just look it up in the docs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github:
  url: http://timothymeixell.com
twitter_username: misternu
github_username:  misternu

# Build settings
markdown: kramdown
exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile', 'blog', 'portfolio', 'claude.md']
